# Generated by Django 4.1 on 2022-08-22 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fscohort", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["number"], "verbose_name_plural": "Öğrenciler"},
        ),
    ]
