# Generated by Django 4.1.4 on 2022-12-21 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fscohort', '0002_alter_student_first_name_alter_student_number'),
        ('fscohort', '0002_alter_student_options'),
    ]

    operations = [
    ]
