# Generated by Django 4.1.4 on 2022-12-21 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fscohort', '0005_student_about_student_files_alter_student_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='files',
        ),
    ]
