# version: "3.9" # optional

services:

  frontend:
    container_name: frontend
    image: docker-compose-fronted
    build: ./frontend
    ports:
      - 3000:3000
      - 80:3000
    restart: on-failure
    depends_on:
      - backend # first run backend.

  backend:
    # container_name: backend # optional (default:key)
    image: docker-compose-backend # build, if no image
    build: ./backend # Which folder (project folder) (must be dockerfile in the folder)
    ports: # external:internal ports
      - 8000:8000
    restart: on-failure # when restart
    volumes: # external:internal volumes
      - ./backend/db.sqlite3:/backend/db.sqlite3

# $ docker compose up # compose çalıştır.
# $ docker compose up -d --build # compose daemon aç ve tekrar build et.
# $ docker compose down # compose kapat.